spring.application.name=MyGardenCare
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.error.include-message=always
permapeople.key-id=${API_KEY_ID}
permapeople.key-secret=${API_KEY_SECRET}