spring.application.name=MyGardenCare
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.error.include-message=always

spring.flyway.enabled=true
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration

permapeople.key-id=${API_KEY_ID}
permapeople.key-secret=${API_KEY_SECRET}

application.security.jwt.secret-key=${SECRET_KEY}

springdoc.packages-to-scan=com.sarojini.MyGardenCare.controllers
springdoc.model-and-view-allowed=true
